[package]
name = "vector-exchange"
version = "0.0.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = true
opt-level = 'z'
codegen-units = 1

[dependencies]
leptos = { version = "0.4.10", features = ["csr", "nightly"] }
eeric = "0.0.15"
eeric-interpreter = "0.0.11"
monaco = "0.3.0"
wasm-bindgen = "0.2.87"