name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install npm dependencies
      run: npm ci

    - name: Setup nightly toolchain
      uses: actions-rs/toolchain@v1.0.7
      with:
        toolchain: nightly
        target: wasm32-unknown-unknown
        override: true
    
    - name: Install trunk
      run: cargo install --locked trunk

    - name: Install wasm-bindgen-cli
      run: cargo install --locked wasm-bindgen-cli
    
    - name: Run tests
      run: cargo test --verbose

    - name: WASM and typescript bridge build
      run: npm run build:release

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist/final
    
    
